odot/config/routes.rb
Odot::Application.routes.draw do
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  resources :users
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'todo_lists#index'

end

odot/app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list

  validates :content, presence: true,
                      length: { minimum: 2 }

  scope :complete, -> { where("completed_at is not null") }
  scope :incomplete, -> { where(completed_at: nil) }

  def completed?
    !completed_at.blank?
  end

  def toggle_completion!
    if completed?
      update_attribute(:completed_at, nil)
    else
      update_attribute(:completed_at, Time.now)
    end
  end
end

odot/app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :require_user
  before_action :find_todo_list
  before_action :set_back_link, except: [:index]

  def index
    go_back_link_to todo_lists_path
  end

  def new
    @todo_item = @todo_list.todo_items.new
  end

  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)
    if @todo_item.save
      flash[:success] = "Added todo list item."
      redirect_to todo_list_todo_items_path
    else
      flash[:error] = "There was a problem adding that todo list item."
      render action: :new
    end
  end

  def edit
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  def update
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.update_attributes(todo_item_params)
      flash[:success] = "Saved todo list item."
      redirect_to todo_list_todo_items_path
    else
      flash[:error] = "That todo item could not be saved."
      render action: :edit
    end
  end

  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success] = "Todo list item was deleted."
    else
      flash[:error] = "Todo list item could not be deleted."
    end
    redirect_to todo_list_todo_items_path
  end

  def complete
    @todo_item = @todo_list.todo_items.find(params[:id])
    @todo_item.toggle_completion!
    redirect_to todo_list_todo_items_path, notice: "Todo item updated."
  end

  def url_options
    { todo_list_id: params[:todo_list_id] }.merge(super)
  end

  private
  def set_back_link
    go_back_link_to todo_list_todo_items_path(@todo_list)
  end

  def find_todo_list
    @todo_list = current_user.todo_lists.find(params[:todo_list_id])
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end

end

odot/app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

odot/app/views/todo_items/_form.html.erb
<% if @todo_item.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo item from being saved:</h2>

  <ul>
    <% @todo_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>


<%= form.label :content %>
<%= form.text_field :content %>

<%= form.submit "Save" %>

odot/app/views/todo_items/edit.html.erb
<%= title "Editing Todo Item" %>

<%= form_for [@todo_list, @todo_item] do |form| %>
  <%= render partial: form %>
<% end %>

odot/app/views/todo_items/index.html.erb
<%= title @todo_list.title %>

<ul class="list todo-items no-bullet">
  <% @todo_list.todo_items.each do |todo_item| %>
  <li id="<%= dom_id(todo_item) %>" class="todo-item row">
    <div class="small-2 medium-1 columns checkmark">
      <% if todo_item.completed? %>
        <%= link_to "Mark Incomplete", complete_todo_list_todo_item_path(@todo_list, todo_item), method: :patch, class: "icon-check checked hide-text" %>
      <% else %>
        <%= link_to "Mark Complete", complete_todo_list_todo_item_path(@todo_list, todo_item), method: :patch, class: "icon-check unchecked hide-text" %>
      <% end %>
    </div>
    <div class="small-10 medium-11 columns truncate todo-content" title="<%= todo_item.content %>">
      <%= link_to todo_item.content, edit_todo_list_todo_item_path(@todo_list, todo_item) %>
    </div>
  </li>
  <% end %>
</ul>

odot/app/views/todo_items/new.html.erb
<%= title "Add Item to #{@todo_list.title}" %>

<%= form_for [@todo_list, @todo_item] do |form| %>
  <%= render partial: form %>
<% end %>