odot/config/routes.rb
Odot::Application.routes.draw do
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  resources :users
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'todo_lists#index'

end

odot/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      if params[:remember_me]
        signed_token = Rails.application.message_verifier(:remember_me).generate(user.id)
        cookies.permanent.signed[:remember_me_token] = signed_token
      end
      session[:user_id] = user.id
      flash[:success] = "Thanks for logging in!"
      redirect_to todo_lists_path
    else
      flash[:error] = "There was a problem logging in. Please check your email and password."
      render action: 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    cookies.delete(:remember_me_token)
    reset_session
    redirect_to root_path, notice: "You have been logged out."
  end
end

odot/app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

odot/app/views/user_sessions/new.html.erb
<%= title "Log In" %>

<%= form_tag user_sessions_path do %>
  <%= label_tag :email, "Email Address" %>
  <%= text_field_tag :email, params[:email] %>
  <br />

  <%= label_tag :password, "Password" %>
  <%= password_field_tag :password %>
  <br />
  <%= label_tag :remember_me, "Remember Me?" %>
  <%= check_box_tag :remember_me %>
  <br />

  <%= submit_tag "Log In" %>
  <%= link_to "Forgot Password", new_password_reset_path %>
<% end %>