odot/config/routes.rb
Odot::Application.routes.draw do
  get "/login" => "user_sessions#new", as: :login
  delete "/logout" => "user_sessions#destroy", as: :logout

  resources :users
  resources :user_sessions, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'todo_lists#index'

end

odot/app/views/layouts/_header_logged_in.html.erb
<div class="small-4 columns header-icon">
  <% if @go_back_link_to %>
    <%= link_to "Back", @go_back_link_to, class: "icon-arrow-left hide-text" %>
  <% else %>
    <%= link_to "Sign Out", logout_path, method: :delete, class: "icon-signout hide-text" %>
  <% end %>
</div>
<div class="small-4 columns">
  <h1 class="logo"><%= link_to "Odot", todo_lists_path, class: "hide-text" %></h1>
</div>
<div class="small-4 columns header-icon">
  <%= new_item_link %>
</div>

odot/app/views/layouts/_header_logged_out.html.erb
<div class="small-4 columns header-icon">
  <%= link_to "Sign In", new_user_session_path %>
  <%= link_to "Sign Up", new_user_path %>
</div>
<div class="small-4 columns">
  <h1 class="logo"><%= link_to "Odot", root_path, class: "hide-text" %></h1>
</div>
<div class="small-4 columns header-icon">
</div>

odot/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %>Odot</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |type, message| %>
    <div class="flash alert-box text-center <%= type %>">
      <%= message %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>

  <header class="row global-header">
    <div class="small-12 small-centered medium-8 medium-centered large-5 large-centered columns">
      <% if logged_in? %>
        <%= render partial: 'layouts/header_logged_in' %>
      <% else %>
        <%= render partial: 'layouts/header_logged_out' %>
      <% end %>
    </div>
  </header>

  <div class="row collapse">
    <div class="small-12 small-centered medium-8 medium-centered large-5 large-centered columns">
      <%= yield %>
    </div>
  </div>

  <footer class="row global-footer">
    <div class="small-12 small-centered medium-8 medium-centered large-5 large-centered columns text-center">
      <% if logged_in? %>
        <%= link_to "Settings", edit_user_path(current_user) %>
      <% end %>
    </div>
  </footer>

</body>
</html>